Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/xenial64"
  config.vm.network "private_network", ip: "192.168.34.11"
  config.vm.hostname = "wordpress.local"
  config.vm.provision :shell, :path => "provision.sh"
  config.vm.provision :shell, :path => "installwp.sh", :privileged => false
  config.vm.provision :shell, :path => "restart.sh"
end
